apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
     namespace: default
     name: redis-pvc
  hostPath:
    type: DirectoryOrCreate
    path: "/redis-data"
---
